- name: Demo Play 1
  hosts: all
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello World Testing !!

- name: Demo Play 2
  hosts: localhost
  tasks:
    - name: hallo surya
      ansible.builtin.debug:
        msg: halloo surya sir